# Generated by Django 5.0.6 on 2024-06-18 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catahory',
            new_name='catagory',
        ),
    ]
