# Generated by Django 5.0.6 on 2024-06-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0002_rename_catahory_category_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='catagory',
        ),
    ]
