# Generated by Django 5.0.6 on 2024-06-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0003_remove_category_catagory'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='catagory',
            field=models.ManyToManyField(to='catagories.category'),
        ),
    ]
