# Generated by Django 5.0.6 on 2024-06-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_is_completed_task__completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='_completed',
            new_name='is_completed',
        ),
    ]
